import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MiniDrawer from "@/components/ui/sidebar/sidebar";
import SessionAuthProvider from "@/context/SessionAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionAuthProvider>
          <MiniDrawer>
            {children}
          </MiniDrawer>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
